# fly.toml app configuration file generated for kaiserr-portfolio-server on 2024-11-02T14:56:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kaiserr-portfolio-server'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
# fly.toml file generated for your app
app = "Kaiser-Tanveer's-Portfolio"  # Replace with your app name

kill_signal = "SIGINT"  # Signal used to stop your app
kill_timeout = 5        # Duration to wait before killing your app

[build]
  # If using a specific builder, e.g. for Docker
  # dockerfile = "Dockerfile"

[env]
  # Define environment variables
  NODE_ENV = "production"

[[services]]
  http_checks = []
  
  [http_service]
    # Configure the service
    internal_port = 3000  # Your app's port
    auto_steal = true

    [[http_service.ports]]
      handlers = ["http"]
      port = "80"  # Public port

    [[http_service.ports]]
      handlers = ["tls", "http"]
      port = "443"  # Secure port
